<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Electronics',
                'slug' => 'electronics',
                'description' => 'Latest gadgets, smart devices, and home entertainment products.',
                'image' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Fashion',
                'slug' => 'fashion',
                'description' => 'Everyday fashion essentials, footwear, and premium clothing.',
                'image' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Home & Living',
                'slug' => 'home-living',
                'description' => 'Furniture, decor, lighting, and smart home accessories.',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Sports',
                'slug' => 'sports',
                'description' => 'Performance gear, shoes, and workout essentials.',
                'image' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&h=300&fit=crop',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Beauty',
                'slug' => 'beauty',
                'description' => 'Premium skincare, fragrance, and beauty gift sets.',
                'image' => 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Books',
                'slug' => 'books',
                'description' => 'Popular books for learning, self-improvement, and strategy.',
                'image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
                'is_active' => true,
                'sort_order' => 6,
            ],
        ];

        foreach ($categories as $category) {
            Category::updateOrCreate(
                ['slug' => $category['slug']],
                $category
            );
        }

        $brands = [
            [
                'name' => 'Apple',
                'slug' => 'apple',
                'description' => 'Premium devices and accessories designed for everyday use.',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Samsung',
                'slug' => 'samsung',
                'description' => 'Mobile devices, TVs, and smart electronics.',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Nike',
                'slug' => 'nike',
                'description' => 'Athletic apparel, footwear, and training gear.',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Adidas',
                'slug' => 'adidas',
                'description' => 'Sportswear and performance footwear for active lifestyles.',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Sony',
                'slug' => 'sony',
                'description' => 'Audio, camera, and entertainment products.',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'LG',
                'slug' => 'lg',
                'description' => 'Home appliances, TVs, and lifestyle electronics.',
                'logo' => null,
                'is_active' => true,
            ],
        ];

        foreach ($brands as $brand) {
            Brand::updateOrCreate(
                ['slug' => $brand['slug']],
                $brand
            );
        }

        $categoryIds = Category::whereIn('slug', array_column($categories, 'slug'))
            ->pluck('id', 'slug');

        $brandIds = Brand::whereIn('slug', array_column($brands, 'slug'))
            ->pluck('id', 'slug');

        $products = [
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'apple',
                'name' => 'iPhone 15 Pro Max',
                'short_description' => 'Flagship iPhone with titanium build and pro-grade camera.',
                'description' => 'A high-end smartphone with a powerful chip, premium titanium design, excellent camera system, and all-day battery life.',
                'price' => 1299.99,
                'sale_price' => 1199.99,
                'stock_quantity' => 50,
                'sku' => 'IPH15PM001',
                'main_image' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => true,
                'rating' => 4.8,
                'reviews_count' => 124,
            ],
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'apple',
                'name' => 'MacBook Air M3',
                'short_description' => 'Lightweight laptop with fast performance and long battery life.',
                'description' => 'A thin and portable laptop powered by the M3 chip, suitable for work, study, and everyday creative tasks.',
                'price' => 1399.99,
                'sale_price' => 1299.99,
                'stock_quantity' => 25,
                'sku' => 'MBAIRM3001',
                'main_image' => 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.9,
                'reviews_count' => 88,
            ],
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'samsung',
                'name' => 'Samsung Galaxy S24 Ultra',
                'short_description' => 'Premium Android phone with stylus and AI features.',
                'description' => 'A flagship phone featuring a sharp display, long battery life, advanced camera system, and built-in stylus.',
                'price' => 1199.99,
                'sale_price' => 1099.99,
                'stock_quantity' => 35,
                'sku' => 'SGS24U001',
                'main_image' => 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => true,
                'rating' => 4.7,
                'reviews_count' => 98,
            ],
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'sony',
                'name' => 'Sony WH-1000XM5',
                'short_description' => 'Noise-canceling headphones with premium sound quality.',
                'description' => 'Over-ear headphones designed for deep comfort, clear sound, and excellent active noise cancellation.',
                'price' => 399.99,
                'sale_price' => 349.99,
                'stock_quantity' => 45,
                'sku' => 'SNYWH10005',
                'main_image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.9,
                'reviews_count' => 312,
            ],
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'sony',
                'name' => 'Sony ZV-E10 Camera',
                'short_description' => 'Compact creator camera for video and lifestyle content.',
                'description' => 'A beginner-friendly mirrorless camera optimized for video content, clean audio, and portable shooting.',
                'price' => 799.99,
                'sale_price' => 749.99,
                'stock_quantity' => 18,
                'sku' => 'SNYZVE1001',
                'main_image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => false,
                'rating' => 4.6,
                'reviews_count' => 63,
            ],
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'lg',
                'name' => 'LG OLED evo C4 55',
                'short_description' => 'Premium 55-inch OLED TV with rich contrast and vibrant color.',
                'description' => 'A smart TV with cinematic picture quality, smooth performance, and modern streaming features for home entertainment.',
                'price' => 1499.99,
                'sale_price' => 1329.99,
                'stock_quantity' => 20,
                'sku' => 'LGOLEDC455',
                'main_image' => 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.7,
                'reviews_count' => 74,
            ],
            [
                'category_slug' => 'home-living',
                'brand_slug' => 'lg',
                'name' => 'LG CordZero A9 Vacuum',
                'short_description' => 'Cordless vacuum cleaner with powerful suction.',
                'description' => 'A home cleaning solution with lightweight design, strong suction power, and flexible cleaning attachments.',
                'price' => 599.99,
                'sale_price' => 529.99,
                'stock_quantity' => 22,
                'sku' => 'LGCZA9001',
                'main_image' => 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.4,
                'reviews_count' => 39,
            ],
            [
                'category_slug' => 'sports',
                'brand_slug' => 'nike',
                'name' => 'Nike Air Max 270',
                'short_description' => 'Lifestyle sneakers with bold cushioning and street-ready comfort.',
                'description' => 'Lightweight sneakers featuring responsive cushioning, modern styling, and comfortable everyday support.',
                'price' => 150.00,
                'sale_price' => 119.99,
                'stock_quantity' => 100,
                'sku' => 'NAM270001',
                'main_image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => true,
                'rating' => 4.5,
                'reviews_count' => 215,
            ],
            [
                'category_slug' => 'fashion',
                'brand_slug' => 'nike',
                'name' => 'Nike Dri-FIT T-Shirt',
                'short_description' => 'Breathable training shirt designed for movement.',
                'description' => 'A lightweight workout tee that helps manage sweat and stays comfortable during active sessions.',
                'price' => 35.00,
                'sale_price' => 28.99,
                'stock_quantity' => 150,
                'sku' => 'NKDFT001',
                'main_image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.3,
                'reviews_count' => 56,
            ],
            [
                'category_slug' => 'sports',
                'brand_slug' => 'adidas',
                'name' => 'Adidas Ultraboost 23',
                'short_description' => 'Performance running shoes with energy-return cushioning.',
                'description' => 'A premium running shoe with soft comfort, modern knit upper, and responsive cushioning for everyday training.',
                'price' => 190.00,
                'sale_price' => 169.99,
                'stock_quantity' => 80,
                'sku' => 'AUB23001',
                'main_image' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.7,
                'reviews_count' => 167,
            ],
            [
                'category_slug' => 'fashion',
                'brand_slug' => 'adidas',
                'name' => 'Adidas Essentials Hoodie',
                'short_description' => 'Soft everyday hoodie with a relaxed sporty fit.',
                'description' => 'A comfortable hoodie with clean styling, soft fabric, and easy layering for casual wear.',
                'price' => 65.00,
                'sale_price' => 54.99,
                'stock_quantity' => 90,
                'sku' => 'ADESH001',
                'main_image' => 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.4,
                'reviews_count' => 41,
            ],
            [
                'category_slug' => 'electronics',
                'brand_slug' => 'apple',
                'name' => 'Apple Watch Series 9',
                'short_description' => 'Smartwatch with health tracking and daily convenience features.',
                'description' => 'A versatile smartwatch with fitness tracking, seamless notifications, and a bright display.',
                'price' => 429.99,
                'sale_price' => 389.99,
                'stock_quantity' => 40,
                'sku' => 'AWS9001',
                'main_image' => 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.6,
                'reviews_count' => 91,
            ],
            [
                'category_slug' => 'home-living',
                'brand_slug' => null,
                'name' => 'Luxury Velvet Sofa',
                'short_description' => 'Elegant three-seater sofa with premium velvet finish.',
                'description' => 'A statement living-room sofa with soft velvet upholstery, deep seating, and refined styling.',
                'price' => 899.99,
                'sale_price' => 749.99,
                'stock_quantity' => 15,
                'sku' => 'SOF001',
                'main_image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.6,
                'reviews_count' => 43,
            ],
            [
                'category_slug' => 'home-living',
                'brand_slug' => null,
                'name' => 'Minimalist Desk Lamp',
                'short_description' => 'Clean modern desk lamp with adjustable warm lighting.',
                'description' => 'A stylish lamp for workspaces and bedside tables with simple controls and understated design.',
                'price' => 79.99,
                'sale_price' => null,
                'stock_quantity' => 40,
                'sku' => 'LAMP001',
                'main_image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.5,
                'reviews_count' => 32,
            ],
            [
                'category_slug' => 'beauty',
                'brand_slug' => null,
                'name' => 'Premium Skincare Set',
                'short_description' => 'Complete skincare routine in one premium box.',
                'description' => 'A curated set including cleanser, serum, moisturizer, and daily care essentials for a full routine.',
                'price' => 149.99,
                'sale_price' => 129.99,
                'stock_quantity' => 60,
                'sku' => 'SKS001',
                'main_image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => true,
                'rating' => 4.4,
                'reviews_count' => 89,
            ],
            [
                'category_slug' => 'beauty',
                'brand_slug' => null,
                'name' => 'Luxury Perfume Gift Set',
                'short_description' => 'Five refined fragrances in a gift-ready presentation box.',
                'description' => 'A fragrance discovery set with elegant presentation, suitable for gifting or sampling signature scents.',
                'price' => 199.99,
                'sale_price' => 169.99,
                'stock_quantity' => 30,
                'sku' => 'PERF001',
                'main_image' => 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.7,
                'reviews_count' => 61,
            ],
            [
                'category_slug' => 'beauty',
                'brand_slug' => null,
                'name' => 'Vitamin C Glow Serum',
                'short_description' => 'Brightening face serum for daily skincare use.',
                'description' => 'A lightweight serum designed to support glow, hydration, and a smoother skin appearance.',
                'price' => 39.99,
                'sale_price' => 29.99,
                'stock_quantity' => 120,
                'sku' => 'VITC001',
                'main_image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.5,
                'reviews_count' => 134,
            ],
            [
                'category_slug' => 'books',
                'brand_slug' => null,
                'name' => 'The Art of War',
                'short_description' => 'Classic book on strategy and leadership.',
                'description' => 'A timeless strategy text widely read for its lessons on planning, discipline, and decision-making.',
                'price' => 12.99,
                'sale_price' => null,
                'stock_quantity' => 200,
                'sku' => 'BK001',
                'main_image' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.8,
                'reviews_count' => 528,
            ],
            [
                'category_slug' => 'books',
                'brand_slug' => null,
                'name' => 'Atomic Habits Hardcover',
                'short_description' => 'Bestselling guide to building sustainable habits.',
                'description' => 'A practical self-improvement book focused on small systems, consistency, and long-term personal growth.',
                'price' => 21.99,
                'sale_price' => 18.99,
                'stock_quantity' => 140,
                'sku' => 'BOOKAH001',
                'main_image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
                'rating' => 4.9,
                'reviews_count' => 301,
            ],
            [
                'category_slug' => 'books',
                'brand_slug' => null,
                'name' => 'Deep Work Paperback',
                'short_description' => 'Productivity book for focused, high-value work.',
                'description' => 'A book about building concentration, reducing distraction, and producing better work in less time.',
                'price' => 18.50,
                'sale_price' => 15.99,
                'stock_quantity' => 95,
                'sku' => 'BOOKDW001',
                'main_image' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&h=600&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
                'rating' => 4.6,
                'reviews_count' => 84,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                [
                    'category_id' => $categoryIds[$product['category_slug']],
                    'brand_id' => $product['brand_slug'] ? ($brandIds[$product['brand_slug']] ?? null) : null,
                    'name' => $product['name'],
                    'slug' => Str::slug($product['name']),
                    'short_description' => $product['short_description'],
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'sale_price' => $product['sale_price'],
                    'stock_quantity' => $product['stock_quantity'],
                    'sku' => $product['sku'],
                    'main_image' => $product['main_image'],
                    'is_active' => $product['is_active'],
                    'is_featured' => $product['is_featured'],
                    'is_new_arrival' => $product['is_new_arrival'],
                    'is_best_seller' => $product['is_best_seller'],
                    'rating' => $product['rating'],
                    'reviews_count' => $product['reviews_count'],
                ]
            );
        }
    }
}
